import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('SSH workspace file-transfer controls', () => {
  it('keeps transfer panels attached to their own SSH cards while hidden', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')

    expect(canvas).toContain('const broadcastEnabled = ref(false)')
    expect(canvas).toContain('const broadcastInput = ref(\'\')')
    expect(canvas).toContain('const broadcastEditorOpen = ref(false)')
    expect(canvas).toContain('function sendBroadcast(): void')
    expect(canvas).toContain('Promise.allSettled')
    expect(canvas).toContain('window.terminalAgent.sessions.write(sessionId, data)')
    expect(canvas.match(/class="broadcast-bar"/g)).toHaveLength(1)
    expect(canvas).toContain(':disabled="!broadcastEnabled"')
    expect(canvas).toContain('发送命令到所有会话')
    expect(canvas).toContain('注意：组合键操作跳过发送按键直接发送')
    expect(canvas).toContain('role="switch"')
    expect(canvas).toContain('class="broadcast-switch-control"')
    expect(canvas).toContain('class="broadcast-expand-button"')
    expect(canvas).toContain('function openBroadcastEditor(): void')
    expect(canvas).toContain('class="broadcast-editor-dialog"')
    expect(canvas).toContain('Shift+Enter remains available')
    expect(canvas).toContain('function controlCharacterForKey(event: KeyboardEvent): string | null')
    expect(canvas).toContain("String.fromCharCode(key.charCodeAt(0) - 96)")
    expect(canvas).toContain("import { broadcastCommandPayload } from './broadcast-command'")
    expect(canvas).toContain('const data = broadcastCommandPayload(value)')
    expect(canvas).toContain('const data = broadcastCommandPayload(value, true)')
    expect(canvas).toContain('const broadcastQueue: BroadcastRequest[] = []')
    expect(canvas).toContain('while (broadcastQueue.length > 0)')
    expect(canvas).toContain('request.clearInputValue !== undefined')
    expect(canvas).toContain('发送所有会话执行')
    expect(canvas).toContain('const globalUploadSessionIds = computed(() => [...new Set(')
    expect(canvas).toContain('props.sessions.map(session => session.id)')
    expect(canvas).toContain('function uploadFileToAllConnectedSessions(): Promise<void>')
    expect(canvas).toContain("uploadAll({ sessionIds, remotePath: './' })")
    expect(canvas).toContain('class="broadcast-upload-all-button"')
    expect(canvas).toContain('上传文件到所有会话')
    const broadcastSend = canvas.indexOf('class="broadcast-send-button"')
    const broadcastUpload = canvas.indexOf('class="broadcast-upload-all-button"')
    expect(broadcastUpload).toBeGreaterThan(broadcastSend)

    expect(canvas).toContain('function toggleFileTransfer(sessionId: string): void')
    expect(canvas).toContain('fileTransferPanelSessionIds')
    expect(canvas).toContain('fileTransferVisibleSessionIds')
    expect(canvas).toContain('fileTransferPanelSessionIds.includes(session.id)')
    expect(canvas).toContain('v-show="isFileTransferVisible(session.id)"')
    expect(canvas).toContain('@busy-change="setFileTransferBusy(session.id, $event)"')
    expect(canvas).toContain('文件传输中')
    expect(canvas).toContain('fileTransferPanelSessionIds.value = fileTransferPanelSessionIds.value.filter(sessionId => available.has(sessionId))')
    expect(canvas).not.toContain(':session-ids="orderedCurrentSessions.map(item => item.id)"')
    expect(canvas).not.toContain('class="file-transfer-dock"')
  })

  it('browses authorized local and remote directories with bidirectional transfer actions', () => {
    const panel = readFileSync(new URL('../../../src/renderer/src/components/workbench/FileTransferPanel.vue', import.meta.url), 'utf8')

    expect(panel).toContain('本地（左）')
    expect(panel).toContain('远程（右）')
    expect(panel).toContain('选择本地目录')
    expect(panel).toContain('function refreshLocalDirectory(path?: string): Promise<void>')
    expect(panel).toContain('window.terminalAgent.fileTransfer?.listLocal')
    expect(panel).toContain('window.terminalAgent.fileTransfer?.selectLocalDirectory')
    expect(panel).toContain('function onLocalDrop(event: DragEvent, destinationDirectory = localCurrentPath.value): void')
    expect(panel).toContain('function onRemoteDrop(event: DragEvent, destinationDirectory = remoteCurrentPath.value): void')
    expect(panel).toContain('function onLocalEntryDrop(entry: FileTransferDirectoryEntry, event: DragEvent): void')
    expect(panel).toContain('function onRemoteEntryDrop(entry: FileTransferDirectoryEntry, event: DragEvent): void')
    expect(panel).toContain('startRemoteEntryDrag')
    expect(panel).toContain('startLocalEntryDrag')
    expect(panel).toContain('uploadLocalEntry')
    expect(panel).toContain('downloadRemoteEntry')
    expect(panel).toContain('上传到当前远程目录')
    expect(panel).toContain('下载到当前本地目录')
    expect(panel).toContain('localPath: localSource')
    expect(panel).toContain('localPath: destinationDirectory')
    expect(panel).toContain('directory-authorized transfer boundary')
    expect(panel).toContain("emit('busyChange', value)")
    expect(panel).toContain('文件传输中')
    expect(panel).not.toContain('上传文件到所有会话')
    expect(panel).not.toContain('uploadFileToAllSessions')
    expect(panel).not.toContain('sessionIds?: string[]')
    expect(panel).not.toContain('upload-all-button')
    expect(panel).toContain('文件传输全屏')
    expect(panel).toContain('top: max(52px, calc(env(titlebar-area-height, 0px) + 10px));')
    expect(panel).toContain('top: max(48px, calc(env(titlebar-area-height, 0px) + 8px));')
    expect(panel).toContain('预计剩余')
    expect(panel).not.toContain('recent-local-files')
    expect(panel).not.toContain('localFiles')
  })
})
