import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('ShellCanvas Task 7 reconnect actions', () => {
  it('exposes reconnectable grouped history tabs through the same context menu', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const view = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8')

    expect(canvas).toContain('historyHosts')
    expect(canvas).toContain("@contextmenu.prevent=\"emit('historyMenu', host.id)\"")
    expect(canvas).toContain('host.reconnectable')
    expect(canvas).toContain('host.representativeHistoryId')
    expect(canvas).toContain('重新连接')
    expect(view).toContain(':history-hosts="historyHosts"')
    expect(view).toContain('@reconnect="reconnectShell"')
  })

  it('keeps closed history associations available beside an active terminal after a fresh authority check', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const view = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8')
    const openHistory = view.slice(view.indexOf('async function openShellHistory'), view.indexOf('function closeShellHistory'))

    expect(view).toContain('const historyHosts = computed(() => {')
    expect(view).toContain('function groupHistoryRecords(records: readonly ShellHistorySummary[]): HistoryHost[]')
    expect(view).toContain('function orderHistoryHosts(')
    expect(view).toContain('return orderHistoryHosts(groupHistoryRecords(shellHistory.state.records), shellHistory.state.records, chatStore.state.selectedId)')
    expect(view).toContain('historyOrderByChat')
    expect(canvas).toContain('v-if="historyHosts.length"')
    expect(canvas).not.toContain('v-if="!isLive && historyHosts.length"')
    expect(canvas).toContain("historyMenu: [historyHostId: string]")
    expect(canvas).toContain('defineExpose({ openHistoryMenu })')
    expect(view).toContain('ref="shellCanvas"')
    expect(view).toContain('@history-menu="openHistoricalShellMenu"')
    expect(view).toContain('async function openHistoricalShellMenu(historyHostId: string): Promise<void>')
    expect(view).toContain('shellCanvas.value?.openHistoryMenu(historyHostId)')
    expect(openHistory.indexOf('showHistoryDialog.value = true')).toBeLessThan(openHistory.indexOf('await shellHistory.open({ chatId'))
    expect(openHistory.indexOf('await shellHistory.open({ chatId')).toBeLessThan(openHistory.indexOf('void shellHistory.select(historyId)'))
    expect(openHistory).toContain('historyDialogRequestGeneration')
  })

  it('renders history as independently ordered tabs rather than a multi-select filter', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const view = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8')

    expect(canvas).toContain('历史 SSH 会话')
    expect(canvas).toContain('class="history-session-tab"')
    expect(canvas).toContain('draggable="true"')
    expect(canvas).toContain('@drop="dropHistory(host.id, $event)"')
    expect(canvas).toContain("reorderHistory: [historyIds: string[]]")
    expect(canvas).toContain('handleHistoryHostClick(host)')
    expect(canvas).toContain("emit('reorderHistory', ids)")
    expect(canvas).not.toContain('selectedHistoryHosts')
    expect(canvas).not.toContain('toggleHistoryHost')
    expect(canvas).not.toContain('aria-pressed')
    expect(canvas).toContain('SSH 窗口布局')
    expect(canvas.match(/class="layout-menu"/g)?.length).toBe(1)
    expect(view).toContain('function reorderHistory(historyHostIds: string[]): void')
    expect(view).toContain('@reorder-history="reorderHistory"')
    expect(view).not.toContain('historyPlaybackRecords')
    expect(view).not.toContain('history-shell-card')
  })

  it('labels history without presenting it as the active SSH workspace', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')

    expect(canvas).toContain('SSH工作区')
    expect(canvas).toContain('历史 SSH 连接')
    expect(canvas).toContain('{{ historyHostCount }} 台主机')
    expect(canvas).toContain('当前任务没有在线 SSH')
    expect(canvas).toContain('v-if="isLive" class="shell-title"')
  })

  it('opens the shared Shell History dialog when a historical host is clicked beside live SSH panes', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const view = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8')
    const dialog = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellHistoryDialog.vue', import.meta.url), 'utf8')

    expect(canvas).toContain('function historyTabActive(historyId: string): boolean')
    expect(canvas).toContain('return !hasOnlineSessions.value && activeHistoryId.value === historyId')
    expect(canvas).toContain("emit('history', hostname, historyId)")
    expect(canvas).toContain('openHistoricalSessionHistory(host.hostname, host.representativeHistoryId, host.id)')
    expect(view).toContain('async function openShellHistory(hostname?: string, historyId?: string): Promise<void>')
    expect(view).toContain('void shellHistory.select(historyId)')
    expect(view).toContain(':records="historyDialogRecords"')
    expect(canvas).toContain('v-if="currentSessions.length === 0" class="empty-slot"')
    expect(canvas).not.toContain('class="history-slot"')
    expect(canvas).toContain('v-show="currentSessions.length > 0"')
    expect(canvas).toContain(':aria-label="historyHostActionLabel(host)"')
    expect(view).toContain('@history="openShellHistory"')
    expect(view).toContain(':font-size="layoutPreferences.state.fontSize"')
    expect(dialog).toContain('aria-label="Shell 历史"')
    expect(dialog).toContain('record.hostname')
    expect(dialog).toContain('historyConnectionTimeLabel(record)')
  })

  it('groups history-strip entries by hostname and keeps connection times inside the dialog', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const view = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8')
    const dialog = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellHistoryDialog.vue', import.meta.url), 'utf8')

    expect(view).toContain('function groupHistoryRecords(records: readonly ShellHistorySummary[]): HistoryHost[]')
    expect(view).toContain('recordCount: 1')
    expect(view).toContain('representativeHistoryId: record.id')
    expect(view).toContain('connectionTimeLabel: formatHistoryConnectionTime(record.startedAt)')
    expect(canvas).toContain('return host.hostname')
    expect(canvas).toContain('recordCount')
    expect(canvas).toContain('representativeHistoryId')
    expect(canvas).not.toContain('historyConnectionTimeLabel(host)')
    expect(canvas).not.toContain('<small>已关闭')
    expect(dialog).toContain('record.startedAt')
    expect(canvas).toContain('min-height: 32px')
    expect(canvas).toContain('height: 25px')
    expect(canvas).toContain('font-size: 10px')
  })

  it('vertically centers the closed-Shell history title and summary in their toolbar', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const titleRule = /\.history-shell-heading\s*\{([^}]*)\}/.exec(canvas)?.[1] ?? ''

    expect(titleRule).toContain('align-items: center;')
    expect(titleRule).not.toContain('align-items: baseline;')
  })

  it('removes autonomous upgrade controls from the workbench while preserving compatibility modules', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const chat = readFileSync(new URL('../../../src/renderer/src/components/chat/GlobalChatPanel.vue', import.meta.url), 'utf8')
    const view = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8')

    expect(canvas).not.toContain('已保存会话')
    expect(canvas).not.toContain('升级为全自动驾驶')
    expect(chat).toContain('AI工作区')
    expect(chat).toContain('计划需手动确认')
    expect(chat).not.toContain('辅助驾驶')
    expect(chat).not.toContain('全自动驾驶')
    expect(chat).not.toContain('type="file"')
    expect(chat).not.toContain('添加图片')
    expect(chat).not.toContain('重试')
    expect(view).not.toContain('createAutonomousUpgradeStore')
    expect(view).not.toContain('requestAutonomousUpgrade')
    expect(view).not.toContain('confirmAutonomousUpgrade')
    expect(view).not.toContain(':can-upgrade=')
    expect(view).not.toContain('@upgrade=')
    expect(view).not.toContain('autonomous-upgrade-dialog')
  })

  it('keeps clipboard actions in the terminal context menu and bounds the terminal grid', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const terminal = readFileSync(new URL('../../../src/renderer/src/components/TerminalPane.vue', import.meta.url), 'utf8')
    const shell = readFileSync(new URL('../../../src/renderer/src/components/workbench/WorkbenchShell.vue', import.meta.url), 'utf8')

    expect(terminal).toContain('复制')
    expect(terminal).toContain('粘贴')
    expect(terminal).toContain('全选')
    expect(terminal).toContain('取消选择')
    expect(terminal).toContain('navigator.clipboard')
    expect(terminal).toContain('ref="paneElement"')
    expect(terminal).toContain('paneElement.value?.getBoundingClientRect()')
    expect(terminal).toContain('const bounds = element.getBoundingClientRect()')
    expect(terminal).toContain('if (bounds.width <= 0 || bounds.height <= 0) return')
    const pasteHandler = terminal.slice(terminal.indexOf('async function pasteClipboard'), terminal.indexOf('function selectAll'))
    expect(pasteHandler).toContain('terminal.focus()')
    expect(pasteHandler.indexOf('closeContextMenu()')).toBeLessThan(pasteHandler.indexOf('terminal.focus()'))
    const terminalPaneRule = /\.terminal-pane\s*\{([^}]*)\}/.exec(terminal)?.[1] ?? ''
    const terminalElementRule = /\.terminal-element\s*\{([^}]*)\}/.exec(terminal)?.[1] ?? ''
    expect(terminalPaneRule).toContain('padding: 11px 12px')
    expect(terminalElementRule).not.toContain('padding:')
    expect(terminal).toContain('fontSize: props.fontSize')
    expect(terminal).toContain('terminal.options.fontSize = fontSize')
    expect(canvas).toContain('minmax(0, 1fr)')
    expect(canvas).toContain('min-height: 0')
    expect(canvas).toContain(':font-size="layout.state.fontSize"')
    expect(canvas).toContain('SHELL_FONT_SIZE_OPTIONS')
    expect(canvas).toContain('overflow-x: auto; overflow-y: hidden;')
    expect(canvas).toContain('SSH 窗口布局设置')
    expect(canvas).not.toContain('Maximize2')
    expect(canvas).not.toContain('Minimize2')
    expect(canvas).not.toContain('maximizedSessionId')
    expect(canvas).not.toContain('toggleMaximize')
    expect(shell).toContain('grid-template-rows: 48px minmax(0, 1fr)')
  })

  it('reconciles buffered output once after a terminal pane mounts', () => {
    const terminal = readFileSync(new URL('../../../src/renderer/src/components/TerminalPane.vue', import.meta.url), 'utf8')

    expect(terminal).toContain('function syncTerminalBuffer(): void')
    expect(terminal).toContain('const buffered = props.session.buffer')
    expect(terminal).toContain('initialBufferFrame = window.requestAnimationFrame')
    expect(terminal).toContain('if (event.sessionId === props.session.id) writeTerminalData(event.data)')
    expect(terminal).toContain('window.cancelAnimationFrame(initialBufferFrame)')
  })

  it('allows reordering terminal cards from their title bars', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    expect(canvas).toContain('const draggingSessionId = ref<string | null>(null)')
    expect(canvas).toContain('function dropSession(sessionId: string, event: DragEvent)')
    expect(canvas).toContain('draggable="true"')
    expect(canvas).toContain('@dragstart="beginSessionDrag(session.id, $event)"')
    expect(canvas).toContain('@drop="dropSession(session.id, $event)"')
    expect(canvas).toContain("emit('reorder', ids)")
  })

  it('uses the resolved display label for full-host tooltips instead of a relay route', () => {
    const canvas = readFileSync(new URL('../../../src/renderer/src/components/workbench/ShellCanvas.vue', import.meta.url), 'utf8')
    const tabs = readFileSync(new URL('../../../src/renderer/src/components/SessionTabs.vue', import.meta.url), 'utf8')
    expect(canvas).toContain(':title="sessionDisplayLabel(session, orderedCurrentSessions)"')
    expect(tabs).toContain(':title="sessionDisplayLabel(session, sessions)"')
  })
})
