import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const launcher = readFileSync(new URL('../../../src/renderer/src/components/connections/SshConnectionLauncher.vue', import.meta.url), 'utf8')
const workbench = readFileSync(new URL('../../../src/renderer/src/views/WorkbenchView.vue', import.meta.url), 'utf8').replace(/\r\n/g, '\n')

describe('unified SSH connection launcher', () => {
  it('puts the manual bastion guidance first and leaves direct modes available', () => {
    const bastionMode = launcher.indexOf("{ id: 'bastionHost'")
    const passwordMode = launcher.indexOf("{ id: 'password'")
    const privateKeyMode = launcher.indexOf("{ id: 'privateKey'")

    expect(bastionMode).toBeGreaterThan(-1)
    expect(bastionMode).toBeLessThan(passwordMode)
    expect(passwordMode).toBeLessThan(privateKeyMode)
    expect(launcher).toContain("id: 'password'")
    expect(launcher).toContain("id: 'privateKey'")
    expect(launcher).toContain("id: 'bastionHost'")
    expect(launcher).toContain("label: '堡垒机跳转连接'")
    expect(launcher).toContain("const initialMode = props.editingProfile?.authKind ?? 'bastionHost'")
    expect(launcher).not.toContain('BastionHostForm')
    expect(launcher).not.toContain('BastionLaunchRequest')
    expect(launcher).not.toContain('bastionLaunch:')
    expect(launcher).not.toContain('堡垒机主机地址')
    expect(launcher).not.toContain('唤起终端')
    expect(launcher).toContain('请手动操作')
    expect(launcher).toContain('不会自动填写或唤起堡垒机')
    expect(launcher).toContain('.manual-launch-note { margin: 0 0 2px;')
    expect(launcher).toContain('<template v-if="mode === \'bastionHost\'">')
    expect(launcher).toContain('【配置须知】')
    expect(launcher).toContain('【使用须知】')
    expect(launcher).toContain('06-select-global-putty.png')
    expect(launcher).toContain('07-launch-bastion.png')
    expect(launcher).toContain(':src="sessionConfigImage"')
    expect(launcher).toContain(':src="bastionUsageImage"')

    const bastionPanel = launcher.indexOf('<template v-if="mode === \'bastionHost\'">')
    const notices = launcher.indexOf('<section class="connection-notices"')
    const bastionPanelEnd = launcher.indexOf('</template>', notices)
    expect(notices).toBeGreaterThan(bastionPanel)
    expect(bastionPanelEnd).toBeGreaterThan(notices)
  })

  it('uses a top horizontal tab chooser, a single-column guidance layout, and the same component for embedded and dialog entry points', () => {
    expect(launcher).toContain('aria-orientation="horizontal"')
    expect(launcher).toContain('const launcherInstanceId = `ssh-launcher-${++launcherInstanceCounter}`')
    expect(launcher).toContain(':aria-labelledby="`${launcherInstanceId}-tab-${mode}`"')
    expect(launcher).toContain('.launcher-body { display: flex; flex: 1 1 auto; flex-direction: column;')
    expect(launcher).toContain('.mode-tabs { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(launcher).toContain('.mode-tabs button { display: grid; grid-template-columns: 32px minmax(0, 1fr) 16px;')
    expect(launcher).toContain('.connection-notices { display: grid; grid-template-columns: minmax(0, 1fr);')
    expect(workbench).toContain('<SshConnectionLauncher\n              appearance="embedded"')
    expect(workbench).toContain('<SshConnectionLauncher\n          appearance="dialog"')
  })

  it('keeps the launcher controls fixed while overflowing details scroll and compact containers preserve card text', () => {
    const tabs = launcher.indexOf('<div class="mode-tabs"')
    const scrollRegion = launcher.indexOf('<div class="launcher-scroll-region">')
    const panel = launcher.indexOf('<div class="mode-panel"', scrollRegion)

    expect(tabs).toBeGreaterThan(-1)
    expect(scrollRegion).toBeGreaterThan(tabs)
    expect(panel).toBeGreaterThan(scrollRegion)
    expect(launcher).toContain('.appearance-dialog { box-sizing: border-box; width: min(1040px, calc(100vw - 64px)); height: min(100%, 760px); max-height: 100%; overflow: hidden;')
    expect(launcher).toContain('.appearance-embedded { align-self: center; justify-self: center; width: min(100%, 1040px); height: clamp(360px, 72vh, 760px);')
    expect(launcher).toContain('.launcher-scroll-region { display: flex; align-items: safe center; justify-content: center; flex: 1 1 auto; min-width: 0; min-height: 0; margin-top: 18px; overflow-x: hidden; overflow-y: auto;')
    expect(launcher).toContain('scrollbar-color: transparent transparent;')
    expect(launcher).toContain('.launcher-scroll-region:hover::-webkit-scrollbar-thumb')
    expect(launcher).not.toContain('当前连接方式')
    expect(launcher).not.toContain('mode-panel-heading')
    expect(launcher).toContain('scrollbar-gutter: stable;')
    expect(launcher).toContain('.mode-panel { flex: 0 0 auto; align-self: flex-start; width: 100%; min-width: 0; height: auto;')
    expect(launcher).toContain('container-type: inline-size;')
    expect(launcher).toContain('overflow-wrap: anywhere;')
    expect(launcher).toContain('@container (max-width: 620px)')
    expect(launcher).toContain('@container (max-width: 460px) { .mode-tabs { grid-template-columns: repeat(3, minmax(0, 1fr)); }')
    expect(launcher).toContain('.mode-tab-copy::after,.mode-tab-arrow { display: none; }')
    expect(workbench).toContain('.empty-state { display: grid; align-content: safe center; height: 100%;')
    expect(workbench).toContain('.connection-modal { position: fixed; z-index: 10; inset: 57px 9px 9px; display: grid; align-content: safe center; justify-content: center; box-sizing: border-box;')
  })
})
