export const implementedPrototypeActions = [
  'chatSessions.create',
  'chatSessions.select-live',
  'chatSessions.select-history',
  'chatSessions.restore-live',
  'shellCanvas.layout',
  'shellCanvas.focus',
  'shellCanvas.close',
  'shellCanvas.maximize',
  'shellCanvas.duplicate',
  'shellCanvas.reconnect',
  'shellCanvas.history',
  'settings.routing',
  'settings.llm-profiles',
  'settings.vlm-profiles',
  'settings.fence',
  'settings.appearance',
  'settings.memory',
  'ssh.cmdb',
  'ssh.bastion-host',
  'ssh.password',
  'ssh.private-key',
] as const
