import { createRequire } from 'node:module'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

type ReleaseArtifactInspection = {
  ready: boolean
  skipped: boolean
  runtimePath: string
  bridgePath: string
  missingPaths: readonly string[]
  missingRuntimeDependencies?: readonly string[]
}

type ReleaseArtifactGuard = {
  inspectReleaseIntegrationArtifacts(input: {
    projectRoot: string
    platform?: NodeJS.Platform
    existsSync?: (path: string) => boolean
    listPackage?: (path: string) => string[]
    packageDependencies?: Record<string, string>
  }): ReleaseArtifactInspection
  formatReleaseIntegrationArtifactDiagnostic(inspection: ReleaseArtifactInspection): string
}

const require = createRequire(import.meta.url)

function releaseArtifactGuard(): ReleaseArtifactGuard {
  return require('../../scripts/release-integration-artifacts.cjs') as ReleaseArtifactGuard
}

describe('release integration artifact guard', () => {
  it('accepts the unpacked runtime and bridge generated by the Windows packaging task', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const inspection = releaseArtifactGuard().inspectReleaseIntegrationArtifacts({
      projectRoot,
      platform: 'win32',
      existsSync: path => path === runtimePath || path === bridgePath,
    })

    expect(inspection).toEqual({ ready: true, skipped: false, runtimePath, bridgePath, missingPaths: [] })
  })

  it('reports every missing packaged prerequisite with the task 9 build instruction', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const guard = releaseArtifactGuard()
    const inspection = guard.inspectReleaseIntegrationArtifacts({ projectRoot, platform: 'win32', existsSync: () => false })
    const diagnostic = guard.formatReleaseIntegrationArtifactDiagnostic(inspection)

    expect(inspection).toEqual({ ready: false, skipped: false, runtimePath, bridgePath, missingPaths: [runtimePath, bridgePath] })
    expect(diagnostic).toContain(runtimePath)
    expect(diagnostic).toContain(bridgePath)
    expect(diagnostic).toContain('npm run make:win:unpacked')
    expect(diagnostic).toContain('does not package automatically')
  })

  it('reports only the missing unpacked runtime', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const guard = releaseArtifactGuard()
    const inspection = guard.inspectReleaseIntegrationArtifacts({ projectRoot, platform: 'win32', existsSync: path => path === bridgePath })
    const diagnostic = guard.formatReleaseIntegrationArtifactDiagnostic(inspection)

    expect(inspection.missingPaths).toEqual([runtimePath])
    expect(diagnostic).toContain(runtimePath)
    expect(diagnostic).not.toContain(bridgePath)
  })

  it('reports only the missing unpacked bridge', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const guard = releaseArtifactGuard()
    const inspection = guard.inspectReleaseIntegrationArtifacts({ projectRoot, platform: 'win32', existsSync: path => path === runtimePath })
    const diagnostic = guard.formatReleaseIntegrationArtifactDiagnostic(inspection)

    expect(inspection.missingPaths).toEqual([bridgePath])
    expect(diagnostic).toContain(bridgePath)
    expect(diagnostic).not.toContain(runtimePath)
  })

  it.each(['linux', 'darwin'] as const)('skips Windows release artifact checks on %s', platform => {
    let fileChecks = 0
    const inspection = releaseArtifactGuard().inspectReleaseIntegrationArtifacts({
      projectRoot: 'project',
      platform,
      existsSync: () => {
        fileChecks += 1
        return false
      },
    })

    expect(inspection.ready).toBe(true)
    expect(inspection.skipped).toBe(true)
    expect(inspection.missingPaths).toEqual([])
    expect(fileChecks).toBe(0)
  })

  it('拒绝缺少生产依赖或 LangChain 运行时入口的 app.asar', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const asarPath = join(projectRoot, 'release', 'win-unpacked', 'resources', 'app.asar')
    const guard = releaseArtifactGuard()
    const inspection = guard.inspectReleaseIntegrationArtifacts({
      projectRoot,
      platform: 'win32',
      existsSync: path => [runtimePath, bridgePath, asarPath].includes(path),
      listPackage: () => [
        '\\node_modules\\@langchain\\langgraph\\package.json',
      ],
      packageDependencies: {
        '@langchain/core': '^1.2.9',
        '@langchain/langgraph': '^1.4.12',
        zod: '^4.4.3',
      },
    })
    const diagnostic = guard.formatReleaseIntegrationArtifactDiagnostic(inspection)

    expect(inspection.ready).toBe(false)
    expect(inspection.missingRuntimeDependencies).toEqual([
      '@langchain/core/package.json',
      'zod/package.json',
      '@langchain/core/singletons.cjs',
      '@langchain/core/dist/singletons/index.cjs',
    ])
    expect(diagnostic).toContain('@langchain/core/singletons.cjs')
  })
})
