import { createRequire } from 'node:module'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

type ReleaseArtifactInspection = {
  ready: boolean
  runtimePath: string
  bridgePath: string
  missingPaths: readonly string[]
}

type ReleaseArtifactGuard = {
  inspectReleaseIntegrationArtifacts(input: {
    projectRoot: string
    existsSync?: (path: string) => boolean
  }): ReleaseArtifactInspection
  formatReleaseIntegrationArtifactDiagnostic(inspection: ReleaseArtifactInspection): string
}

const require = createRequire(import.meta.url)

function releaseArtifactGuard(): ReleaseArtifactGuard {
  return require('../../scripts/release-integration-artifacts.cjs') as ReleaseArtifactGuard
}

describe('release integration artifact guard', () => {
  it('accepts the unpacked runtime and bridge generated by the Windows packaging task', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const inspection = releaseArtifactGuard().inspectReleaseIntegrationArtifacts({
      projectRoot,
      existsSync: path => path === runtimePath || path === bridgePath,
    })

    expect(inspection).toEqual({ ready: true, runtimePath, bridgePath, missingPaths: [] })
  })

  it('reports every missing packaged prerequisite with the task 9 build instruction', () => {
    const projectRoot = 'project'
    const runtimePath = join(projectRoot, 'release', 'win-unpacked', 'Terminal-Agent-runtime.exe')
    const bridgePath = join(projectRoot, 'release', 'win-unpacked', 'putty.exe')
    const guard = releaseArtifactGuard()
    const inspection = guard.inspectReleaseIntegrationArtifacts({ projectRoot, existsSync: () => false })
    const diagnostic = guard.formatReleaseIntegrationArtifactDiagnostic(inspection)

    expect(inspection).toEqual({ ready: false, runtimePath, bridgePath, missingPaths: [runtimePath, bridgePath] })
    expect(diagnostic).toContain(runtimePath)
    expect(diagnostic).toContain(bridgePath)
    expect(diagnostic).toContain('npm run make:win:unpacked')
    expect(diagnostic).toContain('does not package automatically')
  })
})
